# Generated by Django 4.2.5 on 2023-10-03 01:53

import concerts.models.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your band name', max_length=100)),
                ('gender', models.CharField(choices=[('rk', 'Rock'), ('po', 'Pop'), ('jz', 'Jazz')], default='rk', max_length=2)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('gain', models.FloatField()),
                ('capacity', models.IntegerField(validators=[concerts.models.validators.validate_capacity])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80, validators=[django.core.validators.EmailValidator('no es un mail valido')])),
                ('password', models.CharField(max_length=20, validators=[concerts.models.validators.validate_password])),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=50)),
                ('session', models.CharField(choices=[('user', 'user'), ('po', 'place_owner'), ('bo', 'band_owner')], default='user', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tk', 'Ticket')], default='tk', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[concerts.models.validators.validate_price])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.band')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.user')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.user'),
        ),
        migrations.AddField(
            model_name='band',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.user'),
        ),
    ]
