# Generated by Django 4.2.5 on 2023-10-01 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_place_created_place_updated_users_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tk', 'Ticket')], default='tk', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('placeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.place')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.users')),
            ],
        ),
    ]
