# Generated by Django 4.2.5 on 2023-10-01 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your band name', max_length=100)),
                ('gender', models.CharField(choices=[('rk', 'Rock'), ('po', 'Pop'), ('jz', 'Jazz')], default='rk', max_length=2)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts.users')),
            ],
        ),
    ]
